# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Sidekick Java Agent - Snapshot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/snapshot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          hub pr checkout $PR_NUM
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: git-config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Configure Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: >-
            [
              {
                "id": "thundra-releases",
                "url": "https://repo.thundra.io/content/repositories/thundra-releases",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "sidekick-snapshots",
                "url": "https://repo.thundra.io/content/repositories/sidekick-snapshots",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >-
            [
              {
                "id": "thundra-releases",
                "username": "${{ secrets.THUNDRA_INTERNAL_REPO_USERNAME }}",
                "password": "${{ secrets.THUNDRA_INTERNAL_REPO_PASSWORD }}"
              },
              {
                "id": "sidekick-snapshots",
                "username": "${{ secrets.THUNDRA_INTERNAL_REPO_USERNAME }}",
                "password": "${{ secrets.THUNDRA_INTERNAL_REPO_PASSWORD }}"
              }
            ]
      - name: Build and Release Snapshot with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.SIDEKICK_DEVOPS_GITHUB_ACCESS_TOKEN }}
        run: mvn -q clean install deploy --batch-mode -P release